/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

import AttendanceManagement.AttEmpLeave;
import Distribution.Distribution_GUI;
import Manufacturing.Manufacture;
import OrderPlanning.Ord_Request;
import javax.swing.JDesktopPane;
import payrollAndLoanMngmt.PayrollGUI;
import seminar.Seminar_handling;
import termTestPaperHandling.NewFrame;
import termTestPaperHandling.TermTestGUI;
import AssetsHandling.AssetsGUI;
import static Home.login.uName;

/**
 *
 * @author Sumudu Malshan
 */
public class internal_home extends javax.swing.JInternalFrame {

    /**
     * Creates new form internal
     */
    public internal_home() {
        initComponents();
           ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Dist1 = new javax.swing.JButton();
        btn_Dist2 = new javax.swing.JButton();
        btn_Ord1 = new javax.swing.JButton();
        btn_Ord2 = new javax.swing.JButton();
        btn_Manu1 = new javax.swing.JButton();
        btn_Manu2 = new javax.swing.JButton();
        btn_Term1 = new javax.swing.JButton();
        btn_Term2 = new javax.swing.JButton();
        btn_Att1 = new javax.swing.JButton();
        btn_Att2 = new javax.swing.JButton();
        btn_Fix1 = new javax.swing.JButton();
        btn_Fix2 = new javax.swing.JButton();
        btn_Pay1 = new javax.swing.JButton();
        btn_Pay2 = new javax.swing.JButton();
        btn_Sem1 = new javax.swing.JButton();
        btn_Sem2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setForeground(new java.awt.Color(51, 51, 51));
        setMaximizable(true);
        setEnabled(false);
        setFocusCycleRoot(false);
        setMaximumSize(new java.awt.Dimension(1024, 570));
        setMinimumSize(new java.awt.Dimension(1024, 570));
        setPreferredSize(new java.awt.Dimension(1024, 570));
        setRequestFocusEnabled(false);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVerifyInputWhenFocusTarget(false);
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Dist1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2.png"))); // NOI18N
        btn_Dist1.setBorderPainted(false);
        btn_Dist1.setContentAreaFilled(false);
        btn_Dist1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Dist1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Dist1MouseExited(evt);
            }
        });
        getContentPane().add(btn_Dist1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        btn_Dist2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2-1.png"))); // NOI18N
        btn_Dist2.setBorderPainted(false);
        btn_Dist2.setContentAreaFilled(false);
        btn_Dist2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Dist2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Dist2MouseExited(evt);
            }
        });
        btn_Dist2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Dist2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Dist2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        btn_Ord1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1.png"))); // NOI18N
        btn_Ord1.setBorderPainted(false);
        btn_Ord1.setContentAreaFilled(false);
        btn_Ord1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Ord1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Ord1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Ord1MouseExited(evt);
            }
        });
        btn_Ord1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ord1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Ord1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        btn_Ord2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1-1.png"))); // NOI18N
        btn_Ord2.setBorderPainted(false);
        btn_Ord2.setContentAreaFilled(false);
        btn_Ord2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Ord2MouseExited(evt);
            }
        });
        btn_Ord2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ord2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Ord2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        btn_Manu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3.png"))); // NOI18N
        btn_Manu1.setBorderPainted(false);
        btn_Manu1.setContentAreaFilled(false);
        btn_Manu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Manu1MouseEntered(evt);
            }
        });
        getContentPane().add(btn_Manu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        btn_Manu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3-1.png"))); // NOI18N
        btn_Manu2.setBorderPainted(false);
        btn_Manu2.setContentAreaFilled(false);
        btn_Manu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Manu2MouseExited(evt);
            }
        });
        btn_Manu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Manu2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Manu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        btn_Term1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/4.png"))); // NOI18N
        btn_Term1.setBorderPainted(false);
        btn_Term1.setContentAreaFilled(false);
        btn_Term1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Term1MouseEntered(evt);
            }
        });
        btn_Term1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Term1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Term1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, -1, -1));

        btn_Term2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/4-1.png"))); // NOI18N
        btn_Term2.setBorderPainted(false);
        btn_Term2.setContentAreaFilled(false);
        btn_Term2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Term2MouseExited(evt);
            }
        });
        btn_Term2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Term2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Term2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, -1, -1));

        btn_Att1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/5.png"))); // NOI18N
        btn_Att1.setBorderPainted(false);
        btn_Att1.setContentAreaFilled(false);
        btn_Att1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Att1MouseEntered(evt);
            }
        });
        getContentPane().add(btn_Att1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        btn_Att2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/5-1.png"))); // NOI18N
        btn_Att2.setBorderPainted(false);
        btn_Att2.setContentAreaFilled(false);
        btn_Att2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Att2MouseExited(evt);
            }
        });
        btn_Att2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Att2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Att2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        btn_Fix1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/6.png"))); // NOI18N
        btn_Fix1.setBorderPainted(false);
        btn_Fix1.setContentAreaFilled(false);
        btn_Fix1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Fix1MouseEntered(evt);
            }
        });
        getContentPane().add(btn_Fix1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        btn_Fix2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/6-1.png"))); // NOI18N
        btn_Fix2.setBorderPainted(false);
        btn_Fix2.setContentAreaFilled(false);
        btn_Fix2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Fix2MouseExited(evt);
            }
        });
        btn_Fix2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Fix2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Fix2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        btn_Pay1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/7.png"))); // NOI18N
        btn_Pay1.setBorderPainted(false);
        btn_Pay1.setContentAreaFilled(false);
        btn_Pay1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Pay1MouseEntered(evt);
            }
        });
        btn_Pay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Pay1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Pay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, -1, -1));

        btn_Pay2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/7-1.png"))); // NOI18N
        btn_Pay2.setBorderPainted(false);
        btn_Pay2.setContentAreaFilled(false);
        btn_Pay2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Pay2MouseExited(evt);
            }
        });
        btn_Pay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Pay2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Pay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, -1, -1));

        btn_Sem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/8.png"))); // NOI18N
        btn_Sem1.setBorderPainted(false);
        btn_Sem1.setContentAreaFilled(false);
        btn_Sem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Sem1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Sem1MouseEntered(evt);
            }
        });
        btn_Sem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Sem1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Sem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, -1, -1));

        btn_Sem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/8-1.png"))); // NOI18N
        btn_Sem2.setBorderPainted(false);
        btn_Sem2.setContentAreaFilled(false);
        btn_Sem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Sem2MouseExited(evt);
            }
        });
        btn_Sem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Sem2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Sem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setBounds(0, 0, 1024, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Ord1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Ord1MouseExited
        
        
    }//GEN-LAST:event_btn_Ord1MouseExited

    private void btn_Ord1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ord1ActionPerformed

        // TODO add your handling code here:

    }//GEN-LAST:event_btn_Ord1ActionPerformed

    private void btn_Term1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Term1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Term1ActionPerformed

    private void btn_Pay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Pay1ActionPerformed
      
    }//GEN-LAST:event_btn_Pay1ActionPerformed

    private void btn_Sem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Sem1ActionPerformed
        // TODO add your handling code here:
       // new internal_seminar().setVisible(true);
       // this.dispose();
        
        //internal_seminar patient = new internal_seminar();
        //JDesktopPane.add(patient);
        //patient.setVisible(true);
        
       
        
    }//GEN-LAST:event_btn_Sem1ActionPerformed

    private void btn_Sem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Sem1MouseClicked
         
        //homenew h1=new home();
        //jDesktopPane1.removeAll();
        //this.dispose();
        
        
        
    
    }//GEN-LAST:event_btn_Sem1MouseClicked

    private void btn_Ord1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Ord1MouseClicked
        
    }//GEN-LAST:event_btn_Ord1MouseClicked

    private void btn_Ord1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Ord1MouseEntered
        btn_Ord1.setVisible(false);
        btn_Ord2.setVisible(true);
    }//GEN-LAST:event_btn_Ord1MouseEntered

    private void btn_Dist1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Dist1MouseEntered
        btn_Dist1.setVisible(false);
        btn_Dist2.setVisible(true);
    }//GEN-LAST:event_btn_Dist1MouseEntered

    private void btn_Dist1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Dist1MouseExited
        
        
    }//GEN-LAST:event_btn_Dist1MouseExited

    private void btn_Ord2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Ord2MouseExited
        btn_Ord2.setVisible(false);
        btn_Ord1.setVisible(true);
    }//GEN-LAST:event_btn_Ord2MouseExited

    private void btn_Dist2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Dist2MouseEntered
        
    }//GEN-LAST:event_btn_Dist2MouseEntered

    private void btn_Dist2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Dist2MouseExited
        btn_Dist2.setVisible(false);
        btn_Dist1.setVisible(true);
    }//GEN-LAST:event_btn_Dist2MouseExited

    private void btn_Manu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Manu1MouseEntered
        btn_Manu1.setVisible(false);
        btn_Manu2.setVisible(true);
    }//GEN-LAST:event_btn_Manu1MouseEntered

    private void btn_Manu2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Manu2MouseExited
        btn_Manu2.setVisible(false);
        btn_Manu1.setVisible(true);
    }//GEN-LAST:event_btn_Manu2MouseExited

    private void btn_Term1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Term1MouseEntered
        btn_Term1.setVisible(false);
        btn_Term2.setVisible(true);
    }//GEN-LAST:event_btn_Term1MouseEntered

    private void btn_Term2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Term2MouseExited
        btn_Term2.setVisible(false);
        btn_Term1.setVisible(true);
    }//GEN-LAST:event_btn_Term2MouseExited

    private void btn_Att1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Att1MouseEntered
        btn_Att1.setVisible(false);
        btn_Att2.setVisible(true);
    }//GEN-LAST:event_btn_Att1MouseEntered

    private void btn_Att2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Att2MouseExited
        btn_Att2.setVisible(false);
        btn_Att1.setVisible(true);
    }//GEN-LAST:event_btn_Att2MouseExited

    private void btn_Fix1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Fix1MouseEntered
        btn_Fix1.setVisible(false);
        btn_Fix2.setVisible(true);
    }//GEN-LAST:event_btn_Fix1MouseEntered

    private void btn_Fix2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Fix2MouseExited
        btn_Fix2.setVisible(false);
        btn_Fix1.setVisible(true);
    }//GEN-LAST:event_btn_Fix2MouseExited

    private void btn_Pay1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Pay1MouseEntered
        btn_Pay1.setVisible(false);
        btn_Pay2.setVisible(true);
    }//GEN-LAST:event_btn_Pay1MouseEntered

    private void btn_Pay2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Pay2MouseExited
        btn_Pay2.setVisible(false);
        btn_Pay1.setVisible(true);
    }//GEN-LAST:event_btn_Pay2MouseExited

    private void btn_Sem1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Sem1MouseEntered
        btn_Sem1.setVisible(false);
        btn_Sem2.setVisible(true);
    }//GEN-LAST:event_btn_Sem1MouseEntered

    private void btn_Sem2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Sem2MouseExited
        btn_Sem2.setVisible(false);
        btn_Sem1.setVisible(true);
    }//GEN-LAST:event_btn_Sem2MouseExited

    private void btn_Sem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Sem2ActionPerformed
        
        
        Seminar_handling p1=new Seminar_handling();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.removeAll();
        desktopPane.add(p1).setVisible(true); 
        
        
        
       
        
        
            
        
    }//GEN-LAST:event_btn_Sem2ActionPerformed

    private void btn_Pay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Pay2ActionPerformed
        PayrollGUI p1=new PayrollGUI();
       JDesktopPane desktopPane = getDesktopPane();
       desktopPane.removeAll();
        desktopPane.add(p1).setVisible(true); 
    }//GEN-LAST:event_btn_Pay2ActionPerformed

    private void btn_Term2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Term2ActionPerformed
         NewFrame test=new NewFrame();
       JDesktopPane desktopPane = getDesktopPane();
       desktopPane.removeAll();
        desktopPane.add(test).setVisible(true);
    }//GEN-LAST:event_btn_Term2ActionPerformed

    private void btn_Ord2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ord2ActionPerformed
        Ord_Request test=new Ord_Request();
       JDesktopPane desktopPane = getDesktopPane();
       desktopPane.removeAll();
        desktopPane.add(test).setVisible(true);
    }//GEN-LAST:event_btn_Ord2ActionPerformed

    private void btn_Dist2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Dist2ActionPerformed
        Distribution_GUI test=new Distribution_GUI();
       JDesktopPane desktopPane = getDesktopPane();
       desktopPane.removeAll();
        desktopPane.add(test).setVisible(true);
    }//GEN-LAST:event_btn_Dist2ActionPerformed

    private void btn_Att2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Att2ActionPerformed
       AttEmpLeave test=new AttEmpLeave();
       JDesktopPane desktopPane = getDesktopPane();
       desktopPane.removeAll();
        desktopPane.add(test).setVisible(true);
    }//GEN-LAST:event_btn_Att2ActionPerformed

    private void btn_Manu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Manu2ActionPerformed
        Manufacture test=new Manufacture();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.removeAll();
        desktopPane.add(test).setVisible(true);
    }//GEN-LAST:event_btn_Manu2ActionPerformed

    private void btn_Fix2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Fix2ActionPerformed
        AssetsGUI test=new AssetsGUI();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.removeAll();
        desktopPane.add(test).setVisible(true);
    }//GEN-LAST:event_btn_Fix2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Att1;
    private javax.swing.JButton btn_Att2;
    private javax.swing.JButton btn_Dist1;
    private javax.swing.JButton btn_Dist2;
    private javax.swing.JButton btn_Fix1;
    private javax.swing.JButton btn_Fix2;
    private javax.swing.JButton btn_Manu1;
    private javax.swing.JButton btn_Manu2;
    private javax.swing.JButton btn_Ord1;
    private javax.swing.JButton btn_Ord2;
    private javax.swing.JButton btn_Pay1;
    private javax.swing.JButton btn_Pay2;
    private javax.swing.JButton btn_Sem1;
    private javax.swing.JButton btn_Sem2;
    private javax.swing.JButton btn_Term1;
    private javax.swing.JButton btn_Term2;
    private static javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
