/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package termTestPaperHandling;

import Home.*;
import java.awt.Toolkit;
import javax.swing.JDesktopPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
//import static jdk.nashorn.internal.objects.NativeDate.getDate;
import net.proteanit.sql.DbUtils;
//import termTestPaperHandling.yourinitialframe;
/**
 *
 * @author Sumudu Malshan
 */
public class TermTestGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form internal
     */
        Connection conn=null;
        PreparedStatement pst= null;
        ResultSet rs=null;
        int updtTenderID;
        int updtTenderHistoryID;
    
    public TermTestGUI() {
        initComponents();
           ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
           conn=dbconnect.connect();
           
           
           loadNewTenderProvinceCombo();
           loadTenderTable();
           loadTenderHistoryTable();
           loadschoolProvinceCombo();
           
           //pnlNewTender1.setVisible(false);
           
    }

      public void loadNewTenderProvinceCombo()
    {            
          try {
                String qr= " SELECT * FROM province "  ;
                pst=conn.prepareStatement(qr);
                rs=pst.executeQuery();
            while(rs.next())
            {
       
            term_cmbProvince.addItem(rs.getString("name"));
                
            }
            }catch (SQLException ex) {
                Logger.getLogger(TermTestGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
       
    }
      
    public void loadTenderTable()
    { 
     
        try 
        {
            String tndtblqry= " (SELECT * FROM tender where printingStatus='not complete' AND printingStatus='processing') UNION (SELECT * FROM tender where distStatus='not complete')";
            pst=conn.prepareStatement(tndtblqry);
            rs=pst.executeQuery();
            term_tblCurrentTenders.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e)
        { 
           System.out.println(e);  
        }
    }
    
    public void loadTenderHistoryTable()
    { 
     
        try 
        {
            String tndtblhstqry= " SELECT * FROM tender where printingStatus='complete' AND distStatus='complete' ";
            pst=conn.prepareStatement(tndtblhstqry);
            rs=pst.executeQuery();
            term_tblFinishedTenders.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e)
        { 
           System.out.println(e);  
        }
    }
    
    public void loadschoolProvinceCombo()
    {            
          try {
                String qr= " SELECT * FROM province "  ;
                pst=conn.prepareStatement(qr);
                rs=pst.executeQuery();
            while(rs.next())
            {
       
            term_cmbPrSelect.addItem(rs.getString("name"));
                
            }
            }catch (SQLException ex) {
                Logger.getLogger(TermTestGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
       
    }
    
    public void loadDivisionCombo(String pprovinceName)
    {            
          try {
                String qr= " SELECT * FROM province where name='"+pprovinceName+"'";
                System.out.println(qr);
                pst=conn.prepareStatement(qr);
                rs=pst.executeQuery();
            while(rs.next())
            {
       
            term_cmbDvSelect.addItem(rs.getString("division"));
                
            }
            }catch (SQLException ex) {
                Logger.getLogger(TermTestGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();
        pnlTenders = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        term_lblShowDueDate = new javax.swing.JLabel();
        term_lblErrorDate = new javax.swing.JLabel();
        term_lblShowTenderHistoryId = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        term_btnUpdateDueDate = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        term_calUpdateDueDate = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        term_tblFinishedTenders = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        term_tblCurrentTenders = new javax.swing.JTable();
        background2 = new javax.swing.JLabel();
        pnlTenderPapers = new javax.swing.JPanel();
        term_lblShowTenderId = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        batan = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jComboBox6 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        batan1 = new javax.swing.JButton();
        background1 = new javax.swing.JLabel();
        pnlNewTender = new javax.swing.JPanel();
        term_cmbTerm = new javax.swing.JComboBox();
        term_cmbFromGrade = new javax.swing.JComboBox();
        term_calDDate = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        term_lblErrorIncome = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        term_lblErrorDirector = new javax.swing.JLabel();
        term_calRDate = new com.toedter.calendar.JDateChooser();
        jButton6 = new javax.swing.JButton();
        term_txtDirector = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        term_txtIncome = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        term_txtarDescription = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        term_cmbToGrade = new javax.swing.JComboBox();
        term_cmbProvince = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jlabel34 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pnlSchools = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        term_cmbPrSelect = new javax.swing.JComboBox();
        term_cmbDvSelect = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        term_lblErrorPrinciple = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        term_txtSchoolName = new javax.swing.JTextField();
        term_txtPhone = new javax.swing.JTextField();
        term_lblErrorScName = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        term_arSchoolAddress = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        term_txtEmail = new javax.swing.JTextField();
        term_txtPrinciple = new javax.swing.JTextField();
        term_txtSchoolSearch = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        term_lblErrorAddress = new javax.swing.JLabel();
        term_lblErrorPhone = new javax.swing.JLabel();
        term_lblErrorEmail = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        background4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setForeground(new java.awt.Color(51, 51, 51));
        setMaximizable(true);
        setEnabled(false);
        setFocusCycleRoot(false);
        setMaximumSize(new java.awt.Dimension(1024, 570));
        setMinimumSize(new java.awt.Dimension(1024, 570));
        setPreferredSize(new java.awt.Dimension(1024, 570));
        setRequestFocusEnabled(false);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVerifyInputWhenFocusTarget(false);
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backPanel.setMaximumSize(new java.awt.Dimension(1024, 570));
        backPanel.setMinimumSize(new java.awt.Dimension(1024, 570));
        backPanel.setOpaque(false);
        backPanel.setPreferredSize(new java.awt.Dimension(1024, 570));

        leftPanel.setMaximumSize(new java.awt.Dimension(100, 570));
        leftPanel.setMinimumSize(new java.awt.Dimension(100, 570));
        leftPanel.setOpaque(false);
        leftPanel.setPreferredSize(new java.awt.Dimension(100, 570));
        leftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/termTestPaperHandling/images/schools.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        leftPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 100, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/termTestPaperHandling/images/papers.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        leftPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 100, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/termTestPaperHandling/images/tenders.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        leftPanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/termTestPaperHandling/images/Parcel bills.png"))); // NOI18N
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        leftPanel.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 270, -1, -1));

        rightPanel.setMaximumSize(new java.awt.Dimension(910, 570));
        rightPanel.setMinimumSize(new java.awt.Dimension(910, 570));
        rightPanel.setOpaque(false);
        rightPanel.setPreferredSize(new java.awt.Dimension(910, 570));
        rightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTenders.setBackground(new java.awt.Color(102, 255, 102));
        pnlTenders.setMaximumSize(new java.awt.Dimension(915, 570));
        pnlTenders.setOpaque(false);
        pnlTenders.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setText("Add new tender");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        pnlTenders.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tenders");
        pnlTenders.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Tender history");
        pnlTenders.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Tenders in progress");
        pnlTenders.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        term_lblShowDueDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        term_lblShowDueDate.setForeground(new java.awt.Color(255, 255, 255));
        pnlTenders.add(term_lblShowDueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        term_lblErrorDate.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        term_lblErrorDate.setForeground(new java.awt.Color(255, 255, 255));
        pnlTenders.add(term_lblErrorDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 0, 0));

        term_lblShowTenderHistoryId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        term_lblShowTenderHistoryId.setForeground(new java.awt.Color(255, 255, 255));
        pnlTenders.add(term_lblShowTenderHistoryId, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Change due date");
        pnlTenders.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, -1));

        jLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabel.setText("Due Date");
        pnlTenders.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton9.setText("Delete entry");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        pnlTenders.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 530, -1, -1));

        term_btnUpdateDueDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        term_btnUpdateDueDate.setText("Change");
        term_btnUpdateDueDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                term_btnUpdateDueDateActionPerformed(evt);
            }
        });
        pnlTenders.add(term_btnUpdateDueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Tender id");
        pnlTenders.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, -1, -1));

        term_calUpdateDueDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                term_calUpdateDueDatePropertyChange(evt);
            }
        });
        pnlTenders.add(term_calUpdateDueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, -1));

        jSeparator1.setPreferredSize(new java.awt.Dimension(915, 5));
        pnlTenders.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 310, 1220, 20));

        term_tblFinishedTenders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        term_tblFinishedTenders.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        term_tblFinishedTenders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                term_tblFinishedTendersMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(term_tblFinishedTenders);

        pnlTenders.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 810, 150));

        term_tblCurrentTenders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        term_tblCurrentTenders.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        term_tblCurrentTenders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                term_tblCurrentTendersMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(term_tblCurrentTenders);

        pnlTenders.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 810, 130));

        background2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        background2.setForeground(new java.awt.Color(255, 255, 255));
        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blackbackground.jpg"))); // NOI18N
        pnlTenders.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        rightPanel.add(pnlTenders, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlTenderPapers.setBackground(new java.awt.Color(255, 255, 255));
        pnlTenderPapers.setMaximumSize(new java.awt.Dimension(915, 570));
        pnlTenderPapers.setOpaque(false);
        pnlTenderPapers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        term_lblShowTenderId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        term_lblShowTenderId.setForeground(new java.awt.Color(255, 255, 255));
        pnlTenderPapers.add(term_lblShowTenderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 20, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Paper details");
        pnlTenderPapers.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Subject");
        pnlTenderPapers.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        jButton7.setText("jButton7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        pnlTenderPapers.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 510, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Tender ID");
        pnlTenderPapers.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Grade");
        pnlTenderPapers.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        batan.setText("Add document");
        pnlTenderPapers.add(batan, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, -1, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlTenderPapers.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, -1, -1));
        pnlTenderPapers.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 580, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlTenderPapers.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        pnlTenderPapers.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 700, 200));

        batan1.setText("Browse");
        pnlTenderPapers.add(batan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blackbackground.jpg"))); // NOI18N
        pnlTenderPapers.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        rightPanel.add(pnlTenderPapers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlNewTender.setBackground(new java.awt.Color(0, 0, 255));
        pnlNewTender.setMaximumSize(new java.awt.Dimension(915, 570));
        pnlNewTender.setMinimumSize(new java.awt.Dimension(915, 570));
        pnlNewTender.setOpaque(false);
        pnlNewTender.setPreferredSize(new java.awt.Dimension(915, 570));
        pnlNewTender.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        term_cmbTerm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        pnlNewTender.add(term_cmbTerm, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, -1, -1));

        term_cmbFromGrade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13" }));
        pnlNewTender.add(term_cmbFromGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));
        pnlNewTender.add(term_calDDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Add new tender");
        pnlNewTender.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 150, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Term");
        pnlNewTender.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, -1));

        term_lblErrorIncome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        term_lblErrorIncome.setForeground(new java.awt.Color(255, 0, 0));
        pnlNewTender.add(term_lblErrorIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 100, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Due Date");
        pnlNewTender.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, -1));

        term_lblErrorDirector.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        term_lblErrorDirector.setForeground(new java.awt.Color(255, 0, 0));
        pnlNewTender.add(term_lblErrorDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, -1, -1));

        term_calRDate.setDateFormatString("yyyy-MM-dd");
        pnlNewTender.add(term_calRDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Save tender details");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        pnlNewTender.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, -1, -1));

        term_txtDirector.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                term_txtDirectorKeyReleased(evt);
            }
        });
        pnlNewTender.add(term_txtDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 120, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total income(Rs)");
        pnlNewTender.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        term_txtIncome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                term_txtIncomeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                term_txtIncomeKeyTyped(evt);
            }
        });
        pnlNewTender.add(term_txtIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 120, -1));

        term_txtarDescription.setColumns(20);
        term_txtarDescription.setRows(5);
        jScrollPane2.setViewportView(term_txtarDescription);

        pnlNewTender.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 420, 90));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("description");
        pnlNewTender.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("upto grade");
        pnlNewTender.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 90, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Director approved");
        pnlNewTender.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        jButton10.setText("Back");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        pnlNewTender.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        term_cmbToGrade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13" }));
        pnlNewTender.add(term_cmbToGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, -1, -1));

        pnlNewTender.add(term_cmbProvince, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Province");
        pnlNewTender.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 60, 20));

        jlabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel34.setForeground(new java.awt.Color(255, 255, 255));
        jlabel34.setText("Received Date");
        pnlNewTender.add(jlabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("From grade");
        pnlNewTender.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 90, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blackbackground.jpg"))); // NOI18N
        pnlNewTender.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        rightPanel.add(pnlNewTender, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(915, 570));
        jPanel3.setMinimumSize(new java.awt.Dimension(915, 570));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(915, 570));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("jButton3");
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blackbackground.jpg"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        rightPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlSchools.setBackground(new java.awt.Color(102, 255, 102));
        pnlSchools.setMaximumSize(new java.awt.Dimension(915, 570));
        pnlSchools.setMinimumSize(new java.awt.Dimension(915, 570));
        pnlSchools.setOpaque(false);
        pnlSchools.setPreferredSize(new java.awt.Dimension(915, 570));
        pnlSchools.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Division");
        pnlSchools.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

        term_cmbPrSelect.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        term_cmbPrSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                term_cmbPrSelectMouseClicked(evt);
            }
        });
        term_cmbPrSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                term_cmbPrSelectActionPerformed(evt);
            }
        });
        term_cmbPrSelect.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                term_cmbPrSelectPropertyChange(evt);
            }
        });
        pnlSchools.add(term_cmbPrSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        term_cmbDvSelect.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlSchools.add(term_cmbDvSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("School name");
        pnlSchools.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        term_lblErrorPrinciple.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        term_lblErrorPrinciple.setForeground(new java.awt.Color(255, 0, 0));
        pnlSchools.add(term_lblErrorPrinciple, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Add new school");
        pnlSchools.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Address");
        pnlSchools.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("phone");
        pnlSchools.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, 20));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Principle ");
        pnlSchools.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Email");
        pnlSchools.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        term_txtSchoolName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                term_txtSchoolNameKeyReleased(evt);
            }
        });
        pnlSchools.add(term_txtSchoolName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 250, -1));

        term_txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                term_txtPhoneKeyReleased(evt);
            }
        });
        pnlSchools.add(term_txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 270, -1));

        term_lblErrorScName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        term_lblErrorScName.setForeground(new java.awt.Color(255, 0, 0));
        pnlSchools.add(term_lblErrorScName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        term_arSchoolAddress.setColumns(20);
        term_arSchoolAddress.setRows(5);
        term_arSchoolAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                term_arSchoolAddressKeyReleased(evt);
            }
        });
        jScrollPane5.setViewportView(term_arSchoolAddress);

        pnlSchools.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 250, 60));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Province");
        pnlSchools.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));
        pnlSchools.add(term_txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 270, -1));

        term_txtPrinciple.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                term_txtPrincipleKeyReleased(evt);
            }
        });
        pnlSchools.add(term_txtPrinciple, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 270, -1));
        pnlSchools.add(term_txtSchoolSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 310, -1));

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton13.setText("Search");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        pnlSchools.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        jSeparator2.setPreferredSize(new java.awt.Dimension(915, 5));
        pnlSchools.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 310, 1080, -1));

        jButton12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton12.setText("Delete School");
        pnlSchools.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton11.setText("Update school details");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        pnlSchools.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable2);

        pnlSchools.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 770, 170));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("School handling");
        pnlSchools.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        term_lblErrorAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        term_lblErrorAddress.setForeground(new java.awt.Color(255, 0, 0));
        pnlSchools.add(term_lblErrorAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        term_lblErrorPhone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        term_lblErrorPhone.setForeground(new java.awt.Color(255, 0, 0));
        pnlSchools.add(term_lblErrorPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, -1, -1));

        term_lblErrorEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        term_lblErrorEmail.setForeground(new java.awt.Color(255, 0, 0));
        pnlSchools.add(term_lblErrorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Name");
        pnlSchools.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        background4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blackbackground.jpg"))); // NOI18N
        pnlSchools.add(background4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        rightPanel.add(pnlSchools, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(915, 570));
        jPanel1.setMinimumSize(new java.awt.Dimension(915, 570));
        jPanel1.setPreferredSize(new java.awt.Dimension(915, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        rightPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout backPanelLayout = new javax.swing.GroupLayout(backPanel);
        backPanel.setLayout(backPanelLayout);
        backPanelLayout.setHorizontalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        backPanelLayout.setVerticalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(backPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, -1, -1));

        setBounds(0, 0, 1024, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // removing panels
        rightPanel.removeAll();
        rightPanel.repaint();
        rightPanel.revalidate();
        
        rightPanel.add(pnlTenders);
        rightPanel.repaint();
        rightPanel.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         // removing panels
        rightPanel.removeAll();
        rightPanel.repaint();
        rightPanel.revalidate();
        //adding panels
        
        rightPanel.add(pnlTenderPapers);
        rightPanel.repaint();
        rightPanel.revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // removing panels
        rightPanel.removeAll();
        rightPanel.repaint();
        rightPanel.revalidate();
        //adding panels
        
        rightPanel.add(pnlSchools);
        rightPanel.repaint();
        rightPanel.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(term_txtIncome.getText().isEmpty() || term_txtDirector.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "One or more fields are empty");
            if(term_txtIncome.getText().isEmpty()){
                term_lblErrorIncome.setText("*");
            }
            
            if(term_txtDirector.getText().isEmpty()){
                term_lblErrorDirector.setText("*");
            }
           
        }
        else{
        java.sql.Date dueDate=null;
        java.sql.Date receivedDate=null;
        String province=term_cmbProvince.getSelectedItem().toString();
         receivedDate=new java.sql.Date(term_calRDate.getDate().getTime());
         dueDate=new java.sql.Date(term_calDDate.getDate().getTime());
         int term=Integer.parseInt(term_cmbTerm.getSelectedItem().toString());
         String director=term_txtDirector.getText();
         Double income=Double.parseDouble(term_txtIncome.getText());
         int fromGrade=Integer.parseInt(term_cmbFromGrade.getSelectedItem().toString());
         int toGrade=Integer.parseInt(term_cmbToGrade.getSelectedItem().toString());
         String description=term_txtarDescription.getText();
         int provinceId = 0;
         
         try {
                String qr= " SELECT prID from province where name = '"+province+"'" ;
                pst=conn.prepareStatement(qr);
                rs=pst.executeQuery();
            while(rs.next())
            {
                provinceId=Integer.parseInt(rs.getString("prID"));
            }
            }catch (SQLException ex) {
                Logger.getLogger(TermTestGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
         
         try {
                tender tdnew=new tender(dueDate, provinceId, term, description, receivedDate, income, director, fromGrade, toGrade);
                tenderDA tdDAnew=new tenderDA();
                if(tdDAnew.addNewTender(tdnew)){
                    JOptionPane.showMessageDialog(this, "Insertion successfull");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Insertion failed");
                }
                    
                } catch (SQLException ex) {
                Logger.getLogger(TermTestGUI.class.getName()).log(Level.SEVERE, null, ex);
           }
        loadTenderTable();
        rightPanel.removeAll();
        rightPanel.repaint();
        rightPanel.revalidate();
        
        rightPanel.add(pnlTenders);
        rightPanel.repaint();
        rightPanel.revalidate();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
           // removing panels
        rightPanel.removeAll();
        rightPanel.repaint();
        rightPanel.revalidate();
       
        rightPanel.add(pnlNewTender);
        rightPanel.repaint();
        rightPanel.revalidate();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void term_tblCurrentTendersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_term_tblCurrentTendersMouseClicked
        /*try{
        int row=term_tblCurrentTenders.getSelectedRow();
        String tableClick1=(term_tblCurrentTenders.getModel().getValueAt(row, 0).toString());
        String chngDateqry="select dueDate from tender where tenderID='"+tableClick1+"'";
        pst=conn.prepareStatement(chngDateqry);
        rs=pst.executeQuery();
        if(rs.next()){
            String addDueDate=rs.getString("dueDate");
            term_lblShowDueDate.setText(addDueDate);
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }*/
        int row=term_tblCurrentTenders.getSelectedRow();
        
        updtTenderID=Integer.parseInt(term_tblCurrentTenders.getValueAt(row, 0).toString());
        String chDueDate=term_tblCurrentTenders.getValueAt(row, 1).toString();
        
        term_lblShowDueDate.setText(chDueDate);
    }//GEN-LAST:event_term_tblCurrentTendersMouseClicked

    private void term_btnUpdateDueDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_term_btnUpdateDueDateActionPerformed
        java.sql.Date updtDueDate=null;
        updtDueDate=new java.sql.Date(term_calUpdateDueDate.getDate().getTime());
        try{
        tender tdnew=new tender();
        tdnew.setTenderId(updtTenderID);
        tdnew.setDueDate(updtDueDate);
        tenderDA tdDA=new tenderDA();
        if(tdDA.updateDueDate(tdnew)){
            JOptionPane.showMessageDialog(this, "Due Date updated");
        }
        }
        catch(Exception e){
            
        }
        loadTenderTable();
    }//GEN-LAST:event_term_btnUpdateDueDateActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        rightPanel.removeAll();
        rightPanel.repaint();
        rightPanel.revalidate();
        //adding panels
        
        rightPanel.add(pnlTenders);
        rightPanel.repaint();
        rightPanel.revalidate();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void term_tblFinishedTendersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_term_tblFinishedTendersMouseClicked
        int row=term_tblFinishedTenders.getSelectedRow();
        
        updtTenderHistoryID=Integer.parseInt(term_tblFinishedTenders.getValueAt(row, 0).toString());
        
        term_lblShowTenderHistoryId.setText(String.valueOf(updtTenderHistoryID));
    }//GEN-LAST:event_term_tblFinishedTendersMouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int p=JOptionPane.showConfirmDialog(this, "Do you want to delete?","Delete",JOptionPane.YES_NO_OPTION);
        if (p==0){
        try{
        tender tdnew=new tender();
        tdnew.setTenderId(updtTenderHistoryID);
        tenderDA tdDA=new tenderDA();
        if(tdDA.deleteTender(tdnew)){
            JOptionPane.showMessageDialog(this, "Tender is deleted");
        }
        }
        catch(Exception e){
            
        }
        loadTenderHistoryTable();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void term_calUpdateDueDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_term_calUpdateDueDatePropertyChange
        //JOptionPane.showMessageDialog(this, "jnadjcnjd");
        java.sql.Date dueDate=null;
        java.sql.Date chDueDate=null;
        try{
            String checkDateqry="select dueDate from tender where tenderID='"+updtTenderID+"'";
            pst=conn.prepareStatement(checkDateqry);
            rs=pst.executeQuery();
            while(rs.next())
            {
                dueDate=rs.getDate("dueDate");
                if(chDueDate.before(dueDate)){
                    term_lblErrorDate.setText("due date should be greater than received date");
                }
            }
        }
        catch(Exception e){
            
        }
            
    }//GEN-LAST:event_term_calUpdateDueDatePropertyChange

    private void term_txtIncomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_term_txtIncomeKeyTyped
        
        /*try {
            char c=evt.getKeyChar();
            if(Character.isDigit(c))
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
                term_lblErrorIncome.setText("Numbers ");
      
            
        } catch (Exception e) {
            e.printStackTrace();
        }*/    
    }//GEN-LAST:event_term_txtIncomeKeyTyped

    private void term_txtIncomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_term_txtIncomeKeyReleased
         String decimalPattern = "([0-9]+\\.[0-9]+)";  
         String number=term_txtIncome.getText();  
         boolean match = Pattern.matches(decimalPattern, number);
          if(match==false)
          {
             //Toolkit.getDefaultToolkit().beep();
             term_lblErrorIncome.setText("*Invalid");
          }
          
          else
          {
              term_lblErrorIncome.setText(" ");
              //lblmfErrorBasicSal.setText("");;
          }
          
    }//GEN-LAST:event_term_txtIncomeKeyReleased

    private void term_txtDirectorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_term_txtDirectorKeyReleased
        Character c=evt.getKeyChar();
        if(Character.isDigit(c)){
            evt.consume();
            term_lblErrorDirector.setText("*Invalid");
        }
        else{
            term_lblErrorDirector.setText("");
        }
    }//GEN-LAST:event_term_txtDirectorKeyReleased

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        String schoolName=term_txtSchoolSearch.getText();
        System.out.println(schoolName);
        try{
            String searchSchoolqry="select * from school where name='"+schoolName+"'";
            pst=conn.prepareStatement(searchSchoolqry);
            rs=pst.executeQuery();
            if(rs.next())
            {
                term_txtSchoolName.setText(rs.getString("name"));
                term_arSchoolAddress.setText(rs.getString("address"));
                term_txtPrinciple.setText(rs.getString("principle"));
                term_txtPhone.setText(rs.getString("phone"));
                term_txtEmail.setText(rs.getString("email"));
            }
            else{
                JOptionPane.showMessageDialog(this, "School is not available");
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        school sc1=new school();
        if(term_txtSchoolName.getText().isEmpty() || term_arSchoolAddress.getText().isEmpty() || term_txtPrinciple.getText().isEmpty() || term_txtPhone.getText().isEmpty() || term_txtEmail.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "One or more fields are empty");
            if(term_txtSchoolName.getText().isEmpty()){
                term_lblErrorScName.setText("*");
            }
            
            if(term_arSchoolAddress.getText().isEmpty()){
                term_lblErrorAddress.setText("*");
            }
            if(term_txtPrinciple.getText().isEmpty()){
                term_lblErrorPrinciple.setText("*");
            }
            if(term_txtPhone.getText().isEmpty()){
                term_lblErrorPhone.setText("*");
            }
            if(term_txtEmail.getText().isEmpty()){
                term_lblErrorEmail.setText("*");
            }
            
        }
        else{
            if(!sc1.validate(term_txtEmail.getText().trim())){
                //JOptionPane.showMessageDialog(this, "");
                term_lblErrorEmail.setText("Invalid Email");
            }
            else{
        
        String schoolName=term_txtSchoolName.getText();
        String address=term_arSchoolAddress.getText();
        String principle=term_txtPrinciple.getText();
        String phone=term_txtPhone.getText();
        String email=term_txtEmail.getText();
        int schoolId=0;
        int provinceId=0;
        String division=null;
        try{
            String scIdqry="select * from school where name='"+schoolName+"'";
            pst=conn.prepareStatement(scIdqry);
            rs=pst.executeQuery();
            while(rs.next()){
                schoolId=Integer.parseInt(rs.getString("schoolID"));
                provinceId=Integer.parseInt(rs.getString("provinceID"));
                division=rs.getString("division");
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
        try{
        school sc=new school(schoolId,schoolName,address,principle,provinceId,phone,email,division);
        schoolDA scDA=new schoolDA();
            if(scDA.updateSchool(sc)){
                JOptionPane.showMessageDialog(this, "Updation successful");
            }
        }   
        catch(Exception e){
                
                }
        
        term_txtSchoolSearch.setText("");
        term_txtSchoolName.setText("");
        term_arSchoolAddress.setText("");
        term_txtPrinciple.setText("");
        term_txtPhone.setText("");
        term_txtEmail.setText("");
        }
        
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void term_txtSchoolNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_term_txtSchoolNameKeyReleased
        Character c=evt.getKeyChar();
        if(Character.isDigit(c)){
            evt.consume();
            term_lblErrorScName.setText("*Invalid");
        }
        else{
            term_lblErrorScName.setText("");
        }
    }//GEN-LAST:event_term_txtSchoolNameKeyReleased

    private void term_arSchoolAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_term_arSchoolAddressKeyReleased
        Character c=evt.getKeyChar();
        if(Character.isDigit(c)){
            evt.consume();
            term_lblErrorAddress.setText("*Invalid");
        }
        else{
            term_lblErrorAddress.setText("");
        }
    }//GEN-LAST:event_term_arSchoolAddressKeyReleased

    private void term_txtPrincipleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_term_txtPrincipleKeyReleased
        Character c=evt.getKeyChar();
        if(Character.isDigit(c)){
            evt.consume();
            term_lblErrorPrinciple.setText("*Invalid");
        }
        else{
            term_lblErrorPrinciple.setText("");
        }
    }//GEN-LAST:event_term_txtPrincipleKeyReleased

    private void term_txtPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_term_txtPhoneKeyReleased
        Character c=evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
            term_lblErrorPhone.setText("*Invalid");
        }
        else{
            term_lblErrorPhone.setText("");
        }
        
        int i=term_txtPhone.getText().length();
        if(i>10){
            term_lblErrorPhone.setText("*Invalid");
        }
        else{
            term_lblErrorPhone.setText("");
        }
    }//GEN-LAST:event_term_txtPhoneKeyReleased

    private void term_cmbPrSelectPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_term_cmbPrSelectPropertyChange
       
    }//GEN-LAST:event_term_cmbPrSelectPropertyChange

    private void term_cmbPrSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_term_cmbPrSelectMouseClicked
        
    }//GEN-LAST:event_term_cmbPrSelectMouseClicked

    private void term_cmbPrSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_term_cmbPrSelectActionPerformed
        //String passPrName=term_cmbPrSelect.getSelectedItem().toString();
        //loadDivisionCombo(passPrName);
    }//GEN-LAST:event_term_cmbPrSelectActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backPanel;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background4;
    private javax.swing.JButton batan;
    private javax.swing.JButton batan1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel jLabel;
    private static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel jlabel34;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel pnlNewTender;
    private javax.swing.JPanel pnlSchools;
    private javax.swing.JPanel pnlTenderPapers;
    private javax.swing.JPanel pnlTenders;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTextArea term_arSchoolAddress;
    private javax.swing.JButton term_btnUpdateDueDate;
    private com.toedter.calendar.JDateChooser term_calDDate;
    private com.toedter.calendar.JDateChooser term_calRDate;
    private com.toedter.calendar.JDateChooser term_calUpdateDueDate;
    private javax.swing.JComboBox term_cmbDvSelect;
    private javax.swing.JComboBox term_cmbFromGrade;
    private javax.swing.JComboBox term_cmbPrSelect;
    private javax.swing.JComboBox term_cmbProvince;
    private javax.swing.JComboBox term_cmbTerm;
    private javax.swing.JComboBox term_cmbToGrade;
    private javax.swing.JLabel term_lblErrorAddress;
    private javax.swing.JLabel term_lblErrorDate;
    private javax.swing.JLabel term_lblErrorDirector;
    private javax.swing.JLabel term_lblErrorEmail;
    private javax.swing.JLabel term_lblErrorIncome;
    private javax.swing.JLabel term_lblErrorPhone;
    private javax.swing.JLabel term_lblErrorPrinciple;
    private javax.swing.JLabel term_lblErrorScName;
    private javax.swing.JLabel term_lblShowDueDate;
    private javax.swing.JLabel term_lblShowTenderHistoryId;
    private javax.swing.JLabel term_lblShowTenderId;
    private javax.swing.JTable term_tblCurrentTenders;
    private javax.swing.JTable term_tblFinishedTenders;
    private javax.swing.JTextField term_txtDirector;
    private javax.swing.JTextField term_txtEmail;
    private javax.swing.JTextField term_txtIncome;
    private javax.swing.JTextField term_txtPhone;
    private javax.swing.JTextField term_txtPrinciple;
    private javax.swing.JTextField term_txtSchoolName;
    private javax.swing.JTextField term_txtSchoolSearch;
    private javax.swing.JTextArea term_txtarDescription;
    // End of variables declaration//GEN-END:variables
}
